version: '3.8'

services:
  # 1. Database MongoDB (Chạy ngầm)
  mongo_db:
    image: mongo:latest
    container_name: my_mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Lưu dữ liệu để tắt máy không bị mất

  # 2. Backend (Node.js)
  server:
    build: ./server
    container_name: my_server_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      # Kết nối vào service 'mongo_db' ở trên
      - MONGO_URI=mongodb://mongo_db:27017/my_docker_db
      - PORT=5000

  # 3. Frontend (React)
  client:
    build: ./client
    container_name: my_client_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:5000/api/hello

volumes:
  mongo_data: